name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    permissions:
      packages: write
    runs-on: ubuntu-latest

    steps:
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: takepoint-io
        password: ${{ secrets.GITHUB_TOKEN }}
    - uses: actions/checkout@v4
    - name: Microsoft issue
      run: sudo apt-get install build-essential libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ghcr.io/takepoint-io/takepoint-stats-bot-prod
    - name: Push Docker image to Github Container Registry
      run: docker push ghcr.io/takepoint-io/takepoint-stats-bot-prod:latest
